name: Yonplei
author: B3auX
version: 0.0.1
main: de.b3aux.yonplei.main.Main

api-version: 1.13

commands:
  vanish:
  v:
  spawn:
  sspawn:
  heal:
  chatclear:
  cc:
  wartung:
  werkbank:
  wb:
  tele:
  dwarp:
  swarp:
  fly:
  gm:
  gamemode:
  invsee:
  enderchest:
  ec:
  msg:
  r:
  mute:
  gmute:
  bye:
  slay:
  kopf:
  giveall:
  warns:
  warnyou:
  unsign:
  delwarn:
  break:
  setlore:
  rename:
  report:
  rtp:
  sign:
  pinv:
  pec:
  tp:
  tphere:
  tpa:
  tpaccept:
  tpall:
  day:
  night:
  repair:
  sun:
  trash:
  nv:
  motd:
  enchant:
  clearlag:
  back:
  unmute: